services:
  
  db:
    container_name: db
    hostname: db
    image: postgres
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  
  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: DotnetExam/Dockerfile
    environment:
      ConnectionStrings__Postgres: Host=db;Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}
      Frontend__Url: ${FRONTEND_URL}
    ports:
      - ${API_HTTP_PORT}:8080
    depends_on: 
      - db